### ISSUE TITLE
Other tracking sites

### ISSUE THREAD

**Issue by iamlorro** [alexellis/eyes-in-the-sky#1]
Is it possible for other tracking sites to be added to this?

https://www.flightradar24.com/raspberry-pi
and/ or
https://www.adsbexchange.com/how-to-feed/

**Comment by alexellis** [comment]
Hi there, since these both work from dump1090 app then I'd say yes. I'll put it on my list of things to look into.

**Comment by alexellis** [comment]
Closing as inactive.
